# configuration file for camera lidar calibration
'chessboardProperties': 10, 15, 0.077 # square num along y-axis, square num along x-axis, side length of the square in meters
'pointFileType': 'pcd' # type of the point cloud file
'pointcloud_limit': -50, 50, -50, 50, -3, 3 # limitations for the pointcloud, (xmin, xmax, ymin, ymax, zmin, zmax)
'planeFitParams': 0.1, 0, 1, 0, 50 # max distance in meters, reference normal(1x3), max angle in degree
'planeFitParams_stage_1': 0.1, 0, -1, 0, 50 # max distance in meters, reference normal(1x3), max angle in degree
'planeFitParams_stage_2': 0.1, 0, -1, 0, 50 # max distance in meters, reference normal(1x3), max angle in degree
'distanceMat_T': 0.1 # max distance for the distance map, in meters
'ifRemoveGround': 1 # remove the ground, 1 or 0

'N_SCAN': 32 # scan line of the lidar
'Horizon_SCAN': 1800 # width for the range image
'groundScanInd': 19 # horizontal ring id from the top to bottom
'sensorMountAngle': 0 # approximate pitch angle for the lidar sensor in degree
'groundRemovalAngleT': 2 # ground removal angle threshold in degree
'segmentTheta': 0.3488 # threshold angle for segmentation in radial
'feasibleSegmentValidPointNum': 30
'segmentValidPointNum': 5
'segmentValidLineNum': 3
'horizontal_res': 0.003488 # in radial
'vertical_theta': 6.000,5.677,5.354,5.032,4.709,4.387,4.064,3.742,3.419,3.096,2.774,2.452,2.129,1.806,1.483,1.161,0.838,0.516,0.193,-0.129,-0.451,-0.774,-1.096,-1.419,-1.741,-2.064,-2.387,-2.709,-3.032,-3.354,-3.677,-4.000

'ga_loss_threshold': 500 # ga fitnessLimit for reprojection error
