# configuration file for camera lidar calibration
'chessboardProperties': 10, 15, 0.077 # square num along y-axis, square num along x-axis, side length of the square in meters
'pointFileType': 'pcd' # type of the point cloud file
'pointcloud_limit': -50, 50, -50, 50, -3, 3 # limitations for the pointcloud, (xmin, xmax, ymin, ymax, zmin, zmax)
'planeFitParams': 0.2, 0, -1, 0, 50 # max distance in meters, reference normal(1x3), max angle in degree
'planeFitParams_stage_1': 0.2, 0, -1, 0, 50 # max distance in meters, reference normal(1x3), max angle in degree
'planeFitParams_stage_2': 0.2, 0, -1, 0, 50 # max distance in meters, reference normal(1x3), max angle in degree
'distanceMat_T': 0.1 # max distance for the distance map, in meters
'ifRemoveGround': 1 # remove the ground, 1 or 0

'N_SCAN': 32 # scan line of the lidar
'Horizon_SCAN': 1800 # width for the range image
'groundScanInd': 12 # horizontal ring id from the top to bottom
'sensorMountAngle': 0 # approximate pitch angle for the lidar sensor in degree
'groundRemovalAngleT': 2 # ground removal angle threshold in degree
'segmentTheta': 0.1488 # threshold angle for segmentation in radial, larger value, larger cluster # 0.3488
'feasibleSegmentValidPointNum': 30
'segmentValidPointNum': 5
'segmentValidLineNum': 3
'horizontal_res': 0.003488 # in radial
'vertical_theta': 6.000,5.677,5.354,5.032,2.99,2.66,2.33,2,0.99,0.66,0.33,0,-1,-1.33,-1.66,-2,-4,-4.33,-4.66,-5,-7,-7.33,-7.66,-8,-10,-10.33,-10.66,-11,-13,-13.33,-13.66,-14

'ga_loss_threshold': 500 # ga fitnessLimit for reprojection error
