function gui = createMultiRosbagImageViewFigure(app)
    gui = struct();

    % Open a window and add some menus
    gui.handle = figure( ...
        'Name', 'Image', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'HandleVisibility', 'on', ...
        'Visible', 'off');

    % create an axes to show the image
    gui.axesImageView = axes(...
                            'Parent', gui.handle, ...
                            'Units', 'Normalized', ...
                            'Position', [0 0 1 1], ...
                            'XTickLabel', '', ...
                            'YTickLabel', '', ...
                            'XTick', '', ...
                            'YTick', '', ...
                            'Color', app.defaultBackGroundColor);

end