function gui = createMultiRosbagPointViewFigure(app)
    gui = struct();

    % Open a window and add some menus
    gui.handle = figure( ...
        'Name', 'Point', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'figure', ...
        'HandleVisibility', 'on', ...
        'Visible', 'off');

    % create an axes to show the point
    gui.axesPointView = axes(...
                            'Parent', gui.handle, ...
                            'Units', 'Normalized', ...
                            'Position', [0 0 1 1], ...
                            'XTickLabel', '', ...
                            'YTickLabel', '', ...
                            'ZTickLabel', '', ...
                            'XTick', '', ...
                            'YTick', '', ...
                            'ZTick', '', ...
                            'Color', app.defaultBackGroundColor, ...
                            'PickableParts', 'all', ...
                            'HitTest', 'on', ...
                            'NextPlot', 'replacechildren', ...
                            'Visible', 'on', ...
                            'XLimMode', 'auto', ...
                            'YLimMode', 'auto', ...
                            'ZLimMode', 'auto', ...
                            'DataAspectRatioMode', 'auto', ...
                            'PlotBoxAspectRatioMode', 'auto');

    % set the axes button down function
    gui.axesPointView.ButtonDownFcn = @axesPointViewButtonDownFcn;

    % set the figure button down function
    gui.handle.ButtonDownFcn = @figureButtonDownFcn;

    function axesPointViewButtonDownFcn(hObject, eventdata, handles)
    end

    function figureButtonDownFcn(hObject, eventdata, handles)
    end

end