%% build the mex-cpp file by mex command

OpenCV_INCLUDE_DIRS =   {['-I/opt/ros/kinetic/include/opencv-3.3.1-dev'], ...
                        ['-I/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv']};
PCL_INCLUDE_DIRS = {
    '-I/usr/include/pcl-1.7', ...
    '-I/usr/include/eigen3', ...
    '-I/usr/include', ...
    '-I/usr/include/ni', ...
    '-I/usr/include/openni2', ...
    '-I/usr/include/vtk-6.2', ...
    '-I/usr/include/freetype2', ...
    '-I/usr/include/x86_64-linux-gnu/freetype2', ...
    '-I/usr/include/jsoncpp', ...
    '-I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent', ...
    '-I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include', ...
    '-I/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi', ...
    '-I/usr/include/python2.7', ...
    '-I/usr/include/x86_64-linux-gnu', ...
    '-I/usr/include/hdf5/openmpi', ...
    '-I/usr/include/libxml2', ...
    '-I/usr/include/tcl', ...
};
OpenCV_LIBRARY_DIRS = {
    ['-L','/usr/local/lib'], ...
    ['-L','/usr/lib/x86_64-linux-gnu'], ...
    ['-L','/lib/x86_64-linux-gnu'], ...
};

OpenCV_LIBRARIES = {
    ['-l','opencv_core.so'], ...
};

G2O_INCLUDE_DIRS =   {['-I/usr/local/include']};

G2O_LIBRARY_DIRS = {
    ['-L','/usr/local/lib'], ...
};

G2O_LIBRARIES = {
    ['-l','g2o_types_sba.so'], ...
    ['-l','g2o_solver_csparse.so'], ...
    ['-l','g2o_solver_dense.so'], ...
    ['-l','g2o_solver_eigen.so'], ...
    ['-l','g2o_solver_pcg.so'], ...
    ['-l','g2o_core.so'], ...
    ['-l','g2o_csparse_extension.so'], ...
    ['-l','g2o_interface.so'], ...
    ['-l','g2o_stuff.so'], ...
};

SOPHOUS_INCLUDE_DIRS =   {['-I/usr/local/include'], ...
                            ['-I/usr/include/eigen3']};

%% ======================================================================================== %%
disp('=====================================================================================');
disp('build function EdgeSE3ProjectDirectWithDirstortJacobianMex');
disp('=====================================================================================');
opts = {
    % ['-DDEBUG '], ...
    % ['-std=c++11 '], ...
    ['-DMEASUREMENT_PRE_POINT '], ...
    % ['-DMEASUREMENT_PRE_PAIR '], ...
    ['-D_GLIBCXX_USE_CXX11_ABI=0 '], ...
};
src = {
    ['cpp/EdgeSE3ProjectDirectWithDirstortJacobian.cpp'], ...
    ['cpp/EdgeSE3ProjectDirectWithDirstortJacobianMex.cpp'], ...
};
mex(...
    opts{:}, ...
    src{:}, ...
    SOPHOUS_INCLUDE_DIRS{:}, ...
    '-outdir', ...
    './mex', ...
    '-output', ...
    'EdgeSE3ProjectDirectWithDirstortJacobianMex'); 

%% ======================================================================================== %%
disp('=====================================================================================');
disp('build function euler2se3Mex');
disp('=====================================================================================');
opts = {
    % ['-DDEBUG '], ...
    % ['-std=c++11 '], ...
    ['-D_GLIBCXX_USE_CXX11_ABI=0 '], ...
};
src = {
    ['cpp/euler2se3Mex.cpp'], ...
};
mex(...
    opts{:}, ...
    src{:}, ...
    SOPHOUS_INCLUDE_DIRS{:}, ...
    '-outdir', ...
    './mex', ...
    '-output', ...
    'euler2se3Mex'); 

%% ======================================================================================== %%
disp('=====================================================================================');
disp('build function se32eulerMex');
disp('=====================================================================================');
opts = {
    % ['-DDEBUG '], ...
    % ['-std=c++11 '], ...
    ['-D_GLIBCXX_USE_CXX11_ABI=0 '], ...
};
src = {
    ['cpp/se32eulerMex.cpp'], ...
};
mex(...
    opts{:}, ...
    src{:}, ...
    SOPHOUS_INCLUDE_DIRS{:}, ...
    '-outdir', ...
    './mex', ...
    '-output', ...
    'se32eulerMex'); 

%% ======================================================================================== %%
disp('=====================================================================================');
disp('build function planeMaskMatchingEnergyLossMex');
disp('=====================================================================================');
opts = {
    % ['-DDEBUG '], ...
    ['-DMEASUREMENT_PRE_POINT '], ...
    % ['-DMEASUREMENT_PRE_PAIR '], ...
    % ['-std=c++11 '], ...
    ['-D_GLIBCXX_USE_CXX11_ABI=0 '], ...
};
src = {
    ['cpp/planeMaskMatchingEnergyLossMex.cpp'], ...
};
mex(...
    opts{:}, ...
    src{:}, ...
    SOPHOUS_INCLUDE_DIRS{:}, ...
    '-outdir', ...
    './mex', ...
    '-output', ...
    'planeMaskMatchingEnergyLossMex'); 

%% ======================================================================================== %%
disp('=====================================================================================');
disp('EdgeSE3ProjectDirectWithDirstortG2oLMMex');
disp('=====================================================================================');
opts = {
    % ['-DDEBUG '], ...
    % ['-std=c++11 '], ...
    ['-D_GLIBCXX_USE_CXX11_ABI=0 '], ...
};
src = {
    ['cpp/EdgeSE3ProjectDirectWithDirstortG2oLMMex.cpp'], ...
    ['cpp/EdgeSE3ProjectDirectWithDirstortG2oLM.cpp'], ...
};
mex(...
    opts{:}, ...
    src{:}, ...
    SOPHOUS_INCLUDE_DIRS{:}, ...
    G2O_INCLUDE_DIRS{:}, ...
    G2O_LIBRARY_DIRS{:}, ...
    G2O_LIBRARIES{:}, ...
    '-outdir', ...
    './mex', ...
    '-output', ...
    'EdgeSE3ProjectDirectWithDirstortG2oLMMex'); 